### ISSUE TITLE
Make repo available as a jupyterbook [Epic] 

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/data-science-workflows#52]
We would like the content of this repo to be more readily accessible, to that end we will first convert it to a Jupyterbook, host it on JH pages, and link the book on the opf website. 
 
- [x] add _toc and _config files #53 
- [x] Publish using Github Pages github pages #54
- [x] add jbook link to operate first website. #55

**Comment by MichaelClifford** [comment]
https://github.com/AICoE/okr/issues/4

**Comment by MichaelClifford** [comment]
Jupyterbook can be found here:
https://aicoe-aiops.github.io/data-science-workflows/README.html
