### ISSUE TITLE
Re-org + Polish Repo Content [EPIC]

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/data-science-workflows#73]
We need to reorganize and update the content in this repo to reflect the current best practices and tools used by our team's data science workflow. 

- [x] Write "What is ODH + OPF doc" #76
- [x] Write Short "Access JH Doc" #75
- [x] Write Short "How to use Thoth Tools" #74
- [x] Update "Seldon Serving Doc" - #61 #46
- [x] Add experiment tracking doc #72
- [x] Add Trino/Superset content #44
- [x] Update project-structure doc to reflect general users #48 
- [x] Remove all links to google drive content #65 
- [x] Remove "Data Sciece Projects" docs from repo #66 
- [x] Restructure /docs #69
- [x] Proof read all existing documents 
- [x] Update README to reflect  new structure #77 
- [x] Update _toc.yaml to reflect all changes.

**Comment by MichaelClifford** [comment]
@aakankshaduggal @oindrillac :clap: :clap: :clap: Thanks for all the hard work getting this done :smiley:
